### ISSUE TITLE
Capire il funzionamento delle process virtual machines

### ISSUE THREAD

**Issue by ttplom** [crystal-bit/sala-studio#2]
**Cosa vuoi proporre per la prossima live?**
Credo sarebbe estremamente interessante andare ad analizzare qualche semplice process virtual machine, ovviamente per semplice intendo un programmino di settanta-ottanta righe al massimo, e successivamente provare a ricrearne una che esegua operazioni aritmetiche di base.

**Comment by davcri** [comment]
Ciao @ttplom l'argomento che proponi è particolare. Onestamente non ho conoscenze in quel campo. Sul server discord so che che c'è un ragazzo che lavora come sistemista e magari ne sa di più su questo argomento.

In ogni caso forse non ero stato chiaro nel README del progetto, ma gli argomenti dovrebbero ruotare attorno allo sviluppo dei videogiochi. Ora ho aggiornato un po' le descrizioni per dare più informazioni.
